name: CI
on:
    - push
    - pull_request
jobs:
    install:
        name: Install
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
            - name: Install Dependencies
              run: yarn install --frozen-lockfile
            - name: Compress Node Modules
              run: tar -zcf ./node_modules.tar.gz ./node_modules
            - name: Upload Node Modules Artifact
              uses: actions/upload-artifact@v2
              with:
                name: node_modules
                path: './node_modules.tar.gz'
    test:
        name: Test
        runs-on: ubuntu-latest
        needs: install
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
            - name: Download Node Modules Artifact
              uses: actions/download-artifact@v2
              with:
                name: node_modules
            - name: Decompress Node Modules
              run: tar -xf ./node_modules.tar.gz
            - name: Run Tests
              run: yarn test
    build:
        name: Build
        runs-on: ubuntu-latest
        needs: install
        steps:
            - name: Run Build
              run: yarn build
