name: Integration
on:
    workflow_dispatch:
    push:
        branches-ignore:
            - main
jobs:
    check-version:
        name: Check Version
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Main
                uses: actions/checkout@v2
                with:
                    ref: main
            -   name: Get Main Version
                run: version_main=`echo 'console.log(require("./package.json").version)' | node`
            -   name: Checkout Branch
                uses: actions/checkout@v2
            -   name: Get Branch Version
                run: version_branch=`echo 'console.log(require("./package.json").version)' | node`
            -   name: Check Versions Differ
                run: if [ "$version_main" = "$version_branch" ]; then echo 'branch version must not be the same as main version'; exit 1; fi
    install:
        name: Install
        runs-on: ubuntu-latest
        needs:
            - check-version
        steps:
            -   name: Checkout Branch
                uses: actions/checkout@v2
            -   name: Install Dependencies
                run: yarn install --frozen-lockfile
            -   name: Compress Node Modules
                run: tar -zcf ./node_modules.tar.gz ./node_modules
            -   name: Upload Node Modules Artifact
                uses: actions/upload-artifact@v2
                with:
                    name: node_modules
                    path: './node_modules.tar.gz'
    lint:
        name: Lint
        runs-on: ubuntu-latest
        needs:
            - install
        steps:
            -   name: Checkout Branch
                uses: actions/checkout@v2
            -   name: Download Node Modules Artifact
                uses: actions/download-artifact@v2
                with:
                    name: node_modules
            -   name: Decompress Node Modules
                run: tar -xf ./node_modules.tar.gz
            -   name: Run Linter
                run: yarn lint
    test:
        name: Test
        runs-on: ubuntu-latest
        needs:
            - install
        steps:
            -   name: Checkout Branch
                uses: actions/checkout@v2
            -   name: Download Node Modules Artifact
                uses: actions/download-artifact@v2
                with:
                    name: node_modules
            -   name: Decompress Node Modules
                run: tar -xf ./node_modules.tar.gz
            -   name: Run Tests
                run: yarn test
    build:
        name: Build
        runs-on: ubuntu-latest
        needs:
            - install
        steps:
            -   name: Checkout Branch
                uses: actions/checkout@v2
            -   name: Download Node Modules Artifact
                uses: actions/download-artifact@v2
                with:
                    name: node_modules
            -   name: Decompress Node Modules
                run: tar -xf ./node_modules.tar.gz
            -   name: Run Build
                run: yarn build
